spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:  
    driverClassName: org.h2.Driver

server:
   port: 8089
  
eureka: 
  client: 
    service-url:
     defaultZone:  https://eureka-mito.herokuapp.com/eureka/ #http://localhost:8768/eureka/
    